
spring:
  application:
      name: movement-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/movement_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url-path: /swagger-ui/

server:
  port: ${PORT:0}

path:
  movements: /api/movements